### ISSUE TITLE
Disallow addition of duplicate charts to current question.

### ISSUE THREAD

**Issue by salspaugh** [salspaugh/DataFramer#93]
You can now add the same variable twice to the same question.

**Comment by macfarlandian** [comment]
@salspaugh can you elaborate on how this bug was produced? i can't figure out how it's even possible.

**Comment by salspaugh** [comment]
Unfortunately I don't remember and I also can't imagine how it would happen! Maybe it got fixed... Sorry! I'm just going to close it for now and if we notice it happening we can reopen it.
